version: "3.8"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/reaction_db
    depends_on:
      - db
    restart: always

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reaction_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  
volumes:
  db-data: